### ISSUE TITLE
Use "strawperson" instead of "strawman" in documents

### ISSUE THREAD

**Issue by jpchase** [samuelgoto/WebID#4]
Both the [problem statement](https://code.sgo.to/WebID/) and [proposal](https://code.sgo.to/WebID/proposal/) use the term "strawman". I think using "strawperson" would be more inclusive language.

**Comment by samuelgoto** [comment]
ah! good catch, thanks jason! done, removed the one reference to strawman and moved that into a strawperson! thanks and resolving!
